### ISSUE TITLE
Riot.js 3.0 Support

### ISSUE THREAD

**Issue by believer-ufa** [yavorsky/riot-brunch#14]
Riot.js have new major version. Please can you change you plugin to support new version of Riot.js?

**Comment by yavorsky** [comment]
@believer-ufa Sorry for delay, yes! Thanks for the issue

**Comment by sblondon** [comment]
Could you push the current repository version to npmjs.com so everyone will get the riot 3.0 support easly?

**Comment by yavorsky** [comment]
published **riot-brunch** 0.1.0 with 3.0 support.
Sorry for the delay. If anyone want - could give collaborator rights to maintain this more 	
thoroughly.

**Comment by sblondon** [comment]
Thanks for the offer but we (at work) decided to switch from riotjs to react yesterday so I would not maintain the riot-brunch package properly in the future.
I still hope the new release will help other people.

Cheers

**Comment by yavorsky** [comment]
@sblondon we too and actually that's why I've supported this repo so lazy.
