### ISSUE TITLE
Instantiate compiled tags

### ISSUE THREAD

**Issue by git-toni** [yavorsky/riot-brunch#2]
This is not really an issue, but I thought I might ask here in search of guidance. 
When trying to instantiate a properly compiled tag using riot-brunch plugin, blank content is rendered. Would there be any example projects that I can browse to see how to use this plugin properly?
I leave here a gist with the relevant files: https://gist.github.com/git-toni/c28a0c626234fddc9558

**Comment by yavorsky** [comment]
@git-toni , Hi! Just pushed mini-blog created as example for riot + brunch. Hope it'll help! 
https://github.com/yavorsky/Riot-blog

**Comment by git-toni** [comment]
wow, that's much more than what I asked for, thank you! I will learn from this ( and understand the Exim thing :) )

**Comment by yavorsky** [comment]
@git-toni Contact me for any questions. Also, I recommend to learn more about exim. Especially cool for apps using React. ;)
